Add kwarg to sort CVSS JSON dict before returning it
skontar/cvss pull request #32
Opened 2022-01-25 19:09 UTC by juspence

2022-01-26 14:33 UTC, skontar commented
Hi! Thanks for the contribution.

Please write tests to cover the new functionality. 

Also I believe that dictionaries maintain order only starting with Python 3.7, so I think it should check for Python version and if it is <3.7 throw `NotImplementedError` or maybe return `OrderedDict`?

2022-01-26 16:54 UTC, skontar requested changes

2022-01-26 16:54 UTC, skontar commented on cvss/constants2.py
> +PYTHON_VERSION = sys.version.split()[0]
Seems like the following is a better approach to get the same string?

```
>>> import platform
>>> platform.python_version()
'3.9.9'
```

2022-01-26 17:03 UTC, skontar commented on cvss/cvss2.py
> +            if PYTHON_VERSION < '3.7':
Either use `LooseVersion`:
```
>>> from distutils.version import LooseVersion
>>> LooseVersion("3.60.0") < LooseVersion("3.7")
False
```
Or use `tuple` with `int` comparison:
```
>>> import sys
>>> pvi = sys.version_info.major, sys.version_info.minor
>>> pvi
(3, 9)
>>> pvi < (3, 7)
False
>>> pvi = (3, 60)
>>> pvi < (3, 7)
False
>>> pvi = (3, 6)
>>> pvi < (3, 7)
True
```

2022-01-26 17:14 UTC, juspence commented on cvss/cvss2.py
> +            if PYTHON_VERSION < '3.7':
Hmm, what do you think about always returning an OrderedDict when the user wants to sort the output, no matter what the version is? That way we don't need the same complex logic in two different places (cvss2.py and cvss3.py)

2022-01-26 17:18 UTC, skontar commented on cvss/cvss2.py
> +            if PYTHON_VERSION < '3.7':
If the only purpose is to generate an object to then serialize using `json.dumps`, then surely it will work as intended.

2022-02-19 19:17 UTC, skontar commented
@mprpic, are you planning to review this change?

2022-02-22 00:08 UTC, mprpic approved these changes
LGTM!

2022-02-22 11:13 UTC, merged